- name: write_cookies
  id: write_cookies
  env:
    COOKIES_SECRET: ${{ secrets.COOKIES_SECRET }}
  shell: bash
  run: |
    set -euo pipefail

    mkdir -p data cookies

    if [ -z "${COOKIES_SECRET:-}" ]; then
      echo "ERROR: COOKIES_SECRET is empty. Add repository secret COOKIES_SECRET with cookie JSON array."
      exit 1
    fi

    printf '%s' "$COOKIES_SECRET" > www.instagram.com.cookies.json
    printf '%s' "$COOKIES_SECRET" > data/www.instagram.com.cookies.json
    printf '%s' "$COOKIES_SECRET" > cookies/www.instagram.com.cookies.json

    python - <<'PY'
import json, sys, os, time

paths = [
    "www.instagram.com.cookies.json",
    "data/www.instagram.com.cookies.json",
    "cookies/www.instagram.com.cookies.json"
]

ok = False
for p in paths:
    try:
        with open(p, encoding="utf-8") as f:
            j = json.load(f)
        if isinstance(j, list):
            print("OK parse cookie file:", p, "entries:", len(j))
            ok = True
            break
        else:
            print("Parsed JSON but it's not a list:", p, "type:", type(j).__name__)
    except Exception as e:
        print("Failed to parse", p, ":", repr(e))

if not ok:
    print("ERROR: cookie files not valid JSON list. Make sure COOKIES_SECRET contains a JSON array (e.g. [ {cookie}, {cookie} ])")
    sys.exit(1)
PY
